FROM php:7.4-cli

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libc-client-dev \
        libkrb5-dev \
        libssl-dev \
        libzip-dev \
        unzip \
    && docker-php-ext-configure imap --with-kerberos --with-imap-ssl \
    && docker-php-ext-install imap mysqli \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
